#STOCKDATE,STOCKCODE,STOCKNAME,TCLOSE,HIGH,LOW,TOPEN,VOTURNOVER,VATURNOVER= \
#               range(0,9) 
#Date	Open	High	Low	Close	Volume	Adj Close
               
STOCKDATE,TOPEN,HIGH,LOW,TCLOSE,VOTURNOVER,ADJCLOSE= \
               range(0,7) 
STOCKCODE=0
STOCKNAME=0
VATURNOVER=VOTURNOVER

